"""increase password length

Revision ID: 89a36c47b4d3
Revises: cba853f8d837
Create Date: 2026-02-15 17:23:29.567000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '89a36c47b4d3'
down_revision: Union[str, Sequence[str], None] = 'cba853f8d837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'name',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('User', 'email',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('User', 'password',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_unique_constraint(None, 'User', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.alter_column('User', 'password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('User', 'email',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('User', 'name',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
